spring:
  profiles:
    active: local
    include: secret

  datasource:
    url: jdbc:mysql://database-1.cjsvopo9rkyv.ap-northeast-2.rds.amazonaws.com/team1
    username: juneseok
    password: gkswk123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # 사진 multipart 용량
  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  #    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  freemaker:
    cache: false
  devtools:
    livereload:
      enabled: 'true'
app:
  cors:
    allowedOrigins: http://localhost:3000
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
server:
  port: '8084'
logging:
  level:
    org:
      springframework:
        web:
      hibernate:
        SQL: DEBUG
  jwt:
    key:
      access: base64 {bcrypt} key
      refresh: base64 {bcrypt} key
    max-age:
      access: 1800  # 60 * 60 * 30
      refresh: 604800 # 60 * 60 * 24 * 7

  mail:
    host: smtp.google.com
    port: 587
    username: to.myanimal.official@gmail.com
    password: sozejyhzlocztwnv
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
