spring:
  profiles:
    active: local
    include: secret

  mail :
    host : smtp.google.com
    port : 587
    username : to.myanimal.official@gmail.com
    password : sozejyhzlocztwnv
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # 사진 multipart 용량
  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/team1
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  #    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  freemaker:
    cache: false
  devtools:
    livereload:
      enabled: 'true'
app:
  cors:
    allowedOrigins: http://localhost:3000
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
server:
  port: '8084'
logging:
  level:
    org:
      springframework:
        web:
      hibernate:
        SQL: DEBUG
