upload:
  image:
<<<<<<< HEAD
    #location: C:\Users\junes\Desktop\Project\data\
    location: D:\archive\codding class\project\To.my animal\datas\
=======
    location: D:\archive\codding class\project\To.my animal\datas\
>>>>>>> f0d3096a97fc2da098b2b2650035b70f70d014bc
