jwt:
  key:
    access: base64 {bcrypt} key
    refresh: base64 {bcrypt} key
  max-age:
    access: 1800  # 60 * 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7


spring:

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'
  datasource:
    password: 'gkswk123'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: juneseok
    url: jdbc:mysql://database-1.cjsvopo9rkyv.ap-northeast-2.rds.amazonaws.com/team1

  mail:
    host: smtp.google.com
    port: 587
    username: to.myanimal.official@gmail.com
    password: sozejyhzlocztwnv
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true